logging.level.root: INFO

config:
  git: "git"
  repositories:
    -
      id: "ev3dev-lang-java"
      path: "repos/ev3dev-lang-java"
      address: "https://github.com/ev3dev-lang-java/ev3dev-lang-java.git"
      authentication: false
      user:
      password:
      build_tool: MAVEN
      main_branch: master
    -
      id: "spring-boot"
      path: "repos/spring-boot"
      address: "https://github.com/spring-projects/spring-boot.git"
      authentication: false
      user:
      password:
      build_tool: MAVEN
      main_branch: master
    -
      id: "spring-framework"
      path: "repos/spring-framework"
      address: "https://github.com/spring-projects/spring-framework.git"
      authentication: false
      user:
      password:
      build_tool: MAVEN
      main_branch: master
